<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Kanis-MBP-2.attlocal.net" failures="1" tests="3" name="Error Validations Test" time="67.442" errors="0" timestamp="2024-07-21T12:59:12 PDT">
  <testcase classname="techniqum.Selenium.tests.ErrorValidationsTest" name="checkOutErrorValidation" time="17.433">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at techniqum.Selenium.tests.ErrorValidationsTest.checkOutErrorValidation(ErrorValidationsTest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- checkOutErrorValidation -->
  <testcase classname="techniqum.Selenium.tests.ErrorValidationsTest" name="loginErrorValidation" time="2.506"/>
  <testcase classname="techniqum.Selenium.tests.ErrorValidationsTest" name="productErrorValidation" time="34.439"/>
</testsuite> <!-- Error Validations Test -->
